version: '3.8'

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
        device: /Users/egauthey/data/wordpress/
        o: bind
        type: none

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /Users/egauthey/data/mariadb/
      o: bind
      type: none

networks:
  inception:

services:
  mariadb:
    build: 
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb-c
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: 
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress-c
    env_file: .env
    ports:
      - 9000:9000
    # depends_on:
    #   - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
    environment:
      - WP_DB_USER=${MYSQL_USER}

  nginx:
    container_name: nginx-c
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    image: nginx
    ports:
      - 443:443
    env_file: .env
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  redis:
    container_name: redis-c
    build: 
      context: ./requirements/bonus/redis
    image: redis
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  adminer:
    container_name: adminer-c
    build: 
      context: ./requirements/bonus/adminer
    image: adminer
    ports:
      - 8080:80
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  # static-website:
  #   build: ./requirements/bonus/staticws
  #   container_name: staticws-c
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - inception
  #   restart: always
