version: '3.8'

volumes:
  db_data:
  wp_data:

networks:
  inception:

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb-c
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress-c
    env_file: .env
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    restart: always